services:
  mcp-bridge:
    build:
      context: .
    develop:
      watch:
        - path: mcp_bridge
          action: rebuild
    container_name: mcp-bridge
    ports:
      - "3989:3989"
    environment:
      - MCP_BRIDGE__CONFIG__FILE=mcp_config.json # mount the config file for this to work
      # - MCP_BRIDGE__CONFIG__HTTP_URL=http://10.88.100.170:8888/config.json
      # - MCP_BRIDGE__CONFIG__JSON=
    volumes:
      - ./mcp_config.json:/mcp_bridge/mcp_config.json
    restart: unless-stopped
